name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        name: checkout the repository
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      
      - name: Init CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java
      
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build
        run: ./gradlew build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1

